sudo: false

language: scala

scala:
- 2.12.7
- 2.11.12
- 2.13.0-M5

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk:
- oraclejdk8
- openjdk8

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

script:
  - sbt ++$TRAVIS_SCALA_VERSION test 

notifications:
  email:
    on_success: always
